### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by agross** [nodenv/nodenv-package-rehash#31]
I am trying to use this on our build server (TeamCity on Linux). While the plugin is installed successfully and hooks automatically into node installations, the plugin errors our as soon as a global package is installed:

```
[01:13:29]Starting: /opt/buildagent/temp/agentTmp/custom_script3893482731796223345
[01:13:29]in directory: /opt/buildagent/work/194256d0fd0f86a9
[01:13:30]/root/.nodenv/versions/10.15.1/bin/yarn -> /root/.nodenv/versions/10.15.1/lib/node_modules/yarn/bin/yarn.js
[01:13:30]/root/.nodenv/versions/10.15.1/bin/yarnpkg -> /root/.nodenv/versions/10.15.1/lib/node_modules/yarn/bin/yarn.js
[01:13:30]
[01:13:30]> yarn@1.13.0 postinstall /root/.nodenv/versions/10.15.1/lib/node_modules/yarn
[01:13:30]> /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall
[01:13:30]sh: 1: /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall: Permission denied
[01:13:30]npm ERR! code ELIFECYCLE
[01:13:30]npm ERR! errno 126
[01:13:30]npm ERR! yarn@1.13.0 postinstall: `/root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall`
[01:13:30]npm ERR! Exit status 126
[01:13:30]npm ERR! 
[01:13:30]npm ERR! Failed at the yarn@1.13.0 postinstall script.
[01:13:30]npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[01:13:30]
[01:13:30]npm ERR! A complete log of this run can be found in:
[01:13:30]npm ERR!     /root/.npm/_logs/2019-02-06T00_13_30_690Z-debug.log
[01:13:30]Process exited with code 126
```

/root/.npm/_logs/2019-02-06T00_13_30_690Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nodenv/versions/10.15.1/bin/node',
1 verbose cli   '/root/.nodenv/versions/10.15.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'yarn' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose npm-session b010a023f8da165f
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/yarn 256ms (from cache)
8 silly pacote tag manifest for yarn@latest fetched in 279ms
9 timing stage:loadCurrentTree Completed in 486ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule yarn@1.13.0 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6ms
18 timing stage:loadIdealTree Completed in 11ms
19 silly currentTree lib
20 silly idealTree lib
20 silly idealTree └── yarn@1.13.0
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 6ms
23 silly diffTrees action count 1
24 silly diffTrees add yarn@1.13.0
25 silly decomposeActions action count 8
26 silly decomposeActions fetch yarn@1.13.0
27 silly decomposeActions extract yarn@1.13.0
28 silly decomposeActions preinstall yarn@1.13.0
29 silly decomposeActions build yarn@1.13.0
30 silly decomposeActions install yarn@1.13.0
31 silly decomposeActions postinstall yarn@1.13.0
32 silly decomposeActions finalize yarn@1.13.0
33 silly decomposeActions refresh-package-json yarn@1.13.0
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
37 verbose lock using /root/.npm/_locks/staging-5d6a950b879dc1f7.lock for /root/.nodenv/versions/10.15.1/lib/node_modules/.staging
38 silly doParallel extract 1
39 silly extract yarn@1.13.0
40 silly tarball trying yarn@latest by hash: sha512-Unfw2eefv8imt4ZMPhvFVP44WCz38huDxkHs+Yqrx4wBTK75Tr0mh3V4rh+2Nw5iQq0rcM/VafotCZo9qTb5DA==
41 silly extract yarn@latest extracted to /root/.nodenv/versions/10.15.1/lib/node_modules/.staging/yarn-32a4c254 (108ms)
42 timing action:extract Completed in 113ms
43 silly doReverseSerial unbuild 8
44 silly doSerial remove 8
45 silly doSerial move 8
46 silly doSerial finalize 8
47 silly finalize /root/.nodenv/versions/10.15.1/lib/node_modules/yarn
48 timing action:finalize Completed in 9ms
49 silly doParallel refresh-package-json 1
50 silly refresh-package-json /root/.nodenv/versions/10.15.1/lib/node_modules/yarn
51 timing action:refresh-package-json Completed in 17ms
52 silly doParallel preinstall 1
53 silly preinstall yarn@1.13.0
54 info lifecycle yarn@1.13.0~preinstall: yarn@1.13.0
55 timing action:preinstall Completed in 2ms
56 silly doSerial build 8
57 silly build yarn@1.13.0
58 info linkStuff yarn@1.13.0
59 silly linkStuff yarn@1.13.0 has /root/.nodenv/versions/10.15.1/lib/node_modules as its parent node_modules
60 silly linkStuff yarn@1.13.0 is part of a global install
61 silly linkStuff yarn@1.13.0 is installed into a global node_modules
62 silly linkStuff yarn@1.13.0 is installed into the top-level global node_modules
63 verbose linkBins [ { yarn: './bin/yarn.js', yarnpkg: './bin/yarn.js' },
63 verbose linkBins   '/root/.nodenv/versions/10.15.1/bin',
63 verbose linkBins   true ]
64 timing action:build Completed in 5ms
65 silly doSerial global-link 8
66 silly doParallel update-linked 0
67 silly doSerial install 8
68 silly install yarn@1.13.0
69 info lifecycle yarn@1.13.0~install: yarn@1.13.0
70 timing action:install Completed in 0ms
71 silly doSerial postinstall 8
72 silly postinstall yarn@1.13.0
73 info lifecycle yarn@1.13.0~postinstall: yarn@1.13.0
74 silly lifecycle yarn@1.13.0~postinstall: no script for postinstall, continuing
75 verbose lifecycle yarn@1.13.0~postinstall: unsafe-perm in lifecycle false
76 verbose lifecycle yarn@1.13.0~postinstall: PATH: /root/.nodenv/versions/10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.nodenv/versions/10.15.1/lib/node_modules/yarn/node_modules/.bin:/root/.nodenv/versions/10.15.1/lib/node_modules/.bin:/root/.nodenv/versions/10.15.1/bin:/root/.nodenv/libexec:/root/.nodenv/plugins/nodenv-update/bin:/root/.nodenv/plugins/nodenv-package-rehash/bin:/root/.nodenv/plugins/node-build/bin:/root/.nodenv/bin:/root/.nodenv/shims:/root/.rbenv/bin:/root/.rbenv/shims:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
77 verbose lifecycle yarn@1.13.0~postinstall: CWD: /root/.nodenv/versions/10.15.1/lib/node_modules/yarn
78 silly lifecycle yarn@1.13.0~postinstall: Args: [ '-c',
78 silly lifecycle   '/root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall' ]
79 silly lifecycle yarn@1.13.0~postinstall: Returned: code: 126  signal: null
80 info lifecycle yarn@1.13.0~postinstall: Failed to exec postinstall script
81 timing action:postinstall Completed in 18ms
82 verbose unlock done using /root/.npm/_locks/staging-5d6a950b879dc1f7.lock for /root/.nodenv/versions/10.15.1/lib/node_modules/.staging
83 timing stage:rollbackFailedOptional Completed in 20ms
84 timing stage:runTopLevelLifecycles Completed in 704ms
85 verbose stack Error: yarn@1.13.0 postinstall: `/root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall`
85 verbose stack Exit status 126
85 verbose stack     at EventEmitter.<anonymous> (/root/.nodenv/versions/10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
85 verbose stack     at EventEmitter.emit (events.js:189:13)
85 verbose stack     at ChildProcess.<anonymous> (/root/.nodenv/versions/10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
85 verbose stack     at ChildProcess.emit (events.js:189:13)
85 verbose stack     at maybeClose (internal/child_process.js:970:16)
85 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
86 verbose pkgid yarn@1.13.0
87 verbose cwd /opt/buildagent/work/194256d0fd0f86a9
88 verbose Linux 4.20.3-200.fc29.x86_64
89 verbose argv "/root/.nodenv/versions/10.15.1/bin/node" "/root/.nodenv/versions/10.15.1/bin/npm" "install" "--global" "yarn"
90 verbose node v10.15.1
91 verbose npm  v6.4.1
92 error code ELIFECYCLE
93 error errno 126
94 error yarn@1.13.0 postinstall: `/root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall`
94 error Exit status 126
95 error Failed at the yarn@1.13.0 postinstall script.
95 error This is probably not a problem with npm. There is likely additional logging output above.
96 verbose exit [ 126, true ]
```

I can run `/root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall` just fine:

```sh
docker exec teamcity-agent-test /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall
nodenv-package-rehash: can't determine target package
```

**Comment by jasonkarns** [comment]
So it's a permissions difference between the user that installed the plugin and the user that is running the `npm i -g yarn` command, yes?

Separate question, though, what is the use case for having this plugin installed on a build box? Globally installed modules would be rare, correct? (The main use case is to not need to run rehash when globals are installed by hand. If you're on a build box, presumably you're not installing globals frequently. And if yarn is the only one you need, I'd recommend having yarn installed as part of the build's base image.)

But regardless, let's look at the permissions... What user/group installed the plugin? What are the permissions on `$(nodenv root)/plugins/nodenv-package-rehash` and also `$(nodenv prefix)/lib/node_modules/.hooks/postinstall` ? And then what is the user account that's running the `npm i -g` command?

**Comment by agross** [comment]
> So it's a permissions difference between the user that installed the plugin and the user that is running the `npm i -g yarn` command, yes?
> What user/group installed the plugin?

I don't think so. Everything runs as root. I am a bit at a loss why permission was denied, that's why I posted.

> What are the permissions on `$(nodenv root)/plugins/nodenv-package-rehash` and also `$(nodenv prefix)/lib/node_modules/.hooks/postinstall` ?

Everything is 755.

```sh
$ docker run -it --rm agross/teamcity-agent:testing bash
root@0e8dab506e23:/# nodenv install 10.15.1
Downloading node-v10.15.1-linux-x64.tar.gz...
-> https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-x64.tar.gz
Installing node-v10.15.1-linux-x64...
Installed node-v10.15.1-linux-x64 to /root/.nodenv/versions/10.15.1

Installed postinstall/postuninstall package hooks for 10.15.1
root@0e8dab506e23:/# echo 10.15.1 > .node-version
root@0e8dab506e23:/# npm i -g yarn
/root/.nodenv/versions/10.15.1/bin/yarn -> /root/.nodenv/versions/10.15.1/lib/node_modules/yarn/bin/yarn.js
/root/.nodenv/versions/10.15.1/bin/yarnpkg -> /root/.nodenv/versions/10.15.1/lib/node_modules/yarn/bin/yarn.js

> yarn@1.13.0 postinstall /root/.nodenv/versions/10.15.1/lib/node_modules/yarn
> /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall
sh: 1: /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! yarn@1.13.0 postinstall: `/root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the yarn@1.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-06T17_03_20_343Z-debug.log
```

I posted the Dockerfile, perhaps you can try for yourself: https://gist.github.com/agross/420a06df3f0ad4974039375d91c7926f

> Separate question, though, what is the use case for having this plugin installed on a build box?

Yes, it's rare. But I thought it would be nice that my users don't have to go through the extra rehash step.

I wonder if it's a problem that sh defaults to dash in the container.

**Comment by jasonkarns** [comment]
> But I thought it would be nice that my users don't have to go through the extra rehash step.

That's why I'm confused... there shouldn't be any users running anything on your build server, right?



> I wonder if it's a problem that sh defaults to dash in the container.

Hmmm... I don't _think_ that should be a problem. The postinstall hook has a shebang of `#!/usr/bin/env bash` so it should still be running as bash... Though is it possible that this build box doesn't have `env` at `/usr/bin/`? Or that `bash` isn't in `PATH`? I'd check those two things next.

Some extra docs from npm: https://docs.npmjs.com/cli/run-script.html
> The actual shell your script is run within is platform dependent. By default, on Unix-like systems it is the /bin/sh command, on Windows it is the cmd.exe. The actual shell referred to by /bin/sh also depends on the system. As of npm@5.1.0 you can customize the shell with the script-shell configuration.

So the scripts within your `package.json#scripts` would be run via `dash`, but the hooks should be executed directly and handled by the interpreter specified in the shebang.

**Comment by jasonkarns** [comment]
Another thing to try as a smoke-test... What if you uninstalled nodenv-package-rehash. Then just placed your own custom postinstall hook?

something like:

```bash
#!/usr/bin/env bash
echo hi
```

written to `$(nodenv prefix)/lib/node_modules/.hooks/postinstall`
(with exec bit flipped)

Then running `npm i -g yarn` to ensure the hook script is invoked correctly. If not, that would indicate some other problem with general npm hook scripts on that box.

**Comment by agross** [comment]
Hm, seems unrelated to the hooks this plugin installs. No idea why.

```sh
$ docker run -it --rm agross/teamcity-agent:testing bash
root@9b776aead2ea:/# echo 10.15.1 > .node-version
root@9b776aead2ea:/# nodenv install
Downloading node-v10.15.1-linux-x64.tar.gz...
-> https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-x64.tar.gz
Installing node-v10.15.1-linux-x64...
Installed node-v10.15.1-linux-x64 to /root/.nodenv/versions/10.15.1

Installed postinstall/postuninstall package hooks for 10.15.1
root@9b776aead2ea:/# ls $(nodenv prefix)/lib/node_modules/.hooks/postinstall -la
lrwxrwxrwx. 1 root root 72 Feb  7 20:14 /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall -> /root/.nodenv/plugins/nodenv-package-rehash/bin/../libexec/nodenv-rehash
root@9b776aead2ea:/# ls -la /root/.nodenv/plugins/nodenv-package-rehash/bin/../libexec/nodenv-rehash
-rwxr-xr-x. 1 root root 1526 Feb  7 18:31 /root/.nodenv/plugins/nodenv-package-rehash/bin/../libexec/nodenv-rehash
root@9b776aead2ea:/# printf '#!/usr/bin/env bash\necho hi\n' > /root/.nodenv/plugins/nodenv-package-rehash/bin/../libexec/nodenv-rehash
root@9b776aead2ea:/# /root/.nodenv/plugins/nodenv-package-rehash/bin/../libexec/nodenv-rehash
hi
root@9b776aead2ea:/# /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall
hi
root@9b776aead2ea:/# npm i -g yarn
/root/.nodenv/versions/10.15.1/bin/yarn -> /root/.nodenv/versions/10.15.1/lib/node_modules/yarn/bin/yarn.js
/root/.nodenv/versions/10.15.1/bin/yarnpkg -> /root/.nodenv/versions/10.15.1/lib/node_modules/yarn/bin/yarn.js

> yarn@1.13.0 postinstall /root/.nodenv/versions/10.15.1/lib/node_modules/yarn
> /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall
sh: 1: /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! yarn@1.13.0 postinstall: `/root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the yarn@1.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-07T20_15_40_054Z-debug.log
```

**Comment by jasonkarns** [comment]
Looks like the same problem as here: https://github.com/creationix/nvm/issues/1407

**Comment by agross** [comment]
Exactly, thanks for th pointer in the right direction!

```sh
$ docker run -it --rm agross/teamcity-agent:testing bash
root@7d53181c383a:/# echo 10.15.1 > .node-version
root@7d53181c383a:/# nodenv install
Downloading node-v10.15.1-linux-x64.tar.gz...
-> https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-x64.tar.gz
Installing node-v10.15.1-linux-x64...
Installed node-v10.15.1-linux-x64 to /root/.nodenv/versions/10.15.1

Installed postinstall/postuninstall package hooks for 10.15.1
root@7d53181c383a:/# npm config set user 0
root@7d53181c383a:/# npm config set unsafe-perm true
root@7d53181c383a:/# npm install -g yarn
/root/.nodenv/versions/10.15.1/bin/yarn -> /root/.nodenv/versions/10.15.1/lib/node_modules/yarn/bin/yarn.js
/root/.nodenv/versions/10.15.1/bin/yarnpkg -> /root/.nodenv/versions/10.15.1/lib/node_modules/yarn/bin/yarn.js

> yarn@1.13.0 postinstall /root/.nodenv/versions/10.15.1/lib/node_modules/yarn
> /root/.nodenv/versions/10.15.1/lib/node_modules/.hooks/postinstall
+ yarn@1.13.0
added 1 package in 1.08s
```
